import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState, useId } from "react";
import Select from "react-select";
import _ from "lodash";
import { useRouter } from "next/router";

export default function selectOption() {
  const router = useRouter();
  const [searchValue, setSearchValue] = useState("");
  const [options, setOptions] = useState([]);
  // Créer un useState tableau qui va stocker les 10 jeux aléatoires
  const [jeux, setJeux] = useState([]);

  // const selectOption = () => {};

  const handleInputChange = _.debounce(function (e) {
    setSearchValue(e);
  }, 300);

  const selectOption = (game) => {
    router.push(`/game/${game.value}`);
  };

  const fetchGames = (searchValue) => {
    fetch(`/api/igdb/games?query=${searchValue}`)
      .then((response) => response.json())
      .then((data) => {
        // Faites quelque chose avec la variable data ici
        const nouveauTableau = data.map(
          (game) =>
            (game = {
              label: game.name,
              value: game.slug,
            })
        );
        setOptions(nouveauTableau);
        console.log(options);
      });
  };

  useEffect(() => {
    if (searchValue.length) {
      fetchGames(searchValue);
    }
  }, [searchValue]);

  useEffect(() => {
    loadRandomGames(10);
  }, []);

  const loadRandomGames = async (nb) => {
    const response = await fetch(`/api/igdb/randomgames?nb=${nb}`);
    const data = await response.json();
    console.log(data);
    // Envoyer les data dans un useState
    setJeux(data);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        // className={styles.main}
        style={{
          background:
            "url(https://sms.hypotheses.org/files/2018/12/36307963371_0d7899fa08_z.jpg)",
          height: "100vh",
          backgroundSize: "cover",
          paddingTop: "100px",
        }}
      >
        <div style={{ maxWidth: "1200px", margin: "auto" }}>
          <h1 className={styles.heading}>
            et si vous decouvrez des nouveau jeux
          </h1>

          <Select
            placeholder="League of Legends"
            instanceId={useId()}
            value={searchValue}
            options={options}
            onChange={selectOption}
            onInputChange={handleInputChange}
          />
          {/* Boucler dans le useState qui contient les 10 jeux */}
        </div>
      </main>
    </>
  );
}
